### ISSUE TITLE
Add test coverage for python scripts

### ISSUE THREAD

**Issue by hillaryj** [cisagov/development-guide#31]
This repository has no actual code testing, a `.coveragerc` file, or a `test` workflow, despite containing python scripts in the `project_setup/scripts` directory and requiring `coverage` in [setup.py](https://github.com/cisagov/development-guide/blob/develop/setup.py).

## Acceptance Criteria

- [ ] Add test coverage for scripts
- [ ] Add `.coveragerc` file
- [ ] Integrate with coveralls

**Comment by mcdonnnj** [comment]
I think we should discuss separating the guide from the tools. It would be nice if the tools were their own package to install instead in my opinion. This would make it easier to add new tools and have a functional CI/CD setup for those tools.

**Comment by jsf9k** [comment]
> I think we should discuss separating the guide from the tools. It would be nice if the tools were their own package to install instead in my opinion. This would make it easier to add new tools and have a functional CI/CD setup for those tools.

I think this is a grand idea.  Do you want to create an issue so we don't lose track of this?

**Comment by hillaryj** [comment]
Issue moved to [cisagov/development-tools #1](https://github.com/cisagov/development-tools/issues/1) via [**ZenHub**](https://www.zenhub.com/)
