### ISSUE TITLE
Instructions for the COOL setup seem outdated

### ISSUE THREAD

**Issue by michaelsaki** [cisagov/development-guide#85]
# 🐛 Summary #

When stepping through the "Setting up a Mac-based development environment" there is a sub section that seems to be outdated: 
"Setup for the COOL". When I attempted to follow the steps each link that was listed just took me to the same COOL repo. 

Also, when investigating the COOL repo, it seems that the repo will be decommissioned in a few months. This leads me to believe that maybe the instructions on the "Setup for the COOL" might need to be removed all together. 

## To reproduce ##

1. Go to this link https://github.com/cisagov/development-guide/blob/develop/dev_envs/mac-env-setup.md
2. Then scroll to the section "Setup for the COOL"
3. Attempt to setup the COOL

## Expected behavior ##

User stepping through the guide should be able to follow the steps successfully to setup the COOL.

**Comment by dav3r** [comment]
The Wiki pages that were linked in that section no longer exist.  The current temporary replacement URLs are below:

- [Install MIT Kerberos](https://github.com/cisagov/cool-system-internal/blob/master/Installing-MIT-Kerberos.md)
- [Configuring Kerberos for the COOL](https://github.com/cisagov/cool-system-internal/blob/master/Configuring-Kerberos-for-the-COOL.md)
- [Configuring your browser for the COOL](https://github.com/cisagov/cool-system-internal/blob/master/Configuring-your-browser-for-the-COOL.md)
- [these instructions to access Guacamole](https://github.com/cisagov/cool-system-internal/blob/master/Accessing-an-assessment-environment-with-Guacamole.md)

@michaelsaki If you could create a PR to update those links, we would very much appreciate that!

**Comment by michaelsaki** [comment]
I believe we can close this, https://github.com/cisagov/development-guide/pull/87 fixed the issue.
