### ISSUE TITLE
Update references to LGTM

### ISSUE THREAD

**Issue by Matthew-Grayson** [cisagov/development-guide#86]
# 🐛 Summary #
LGTM was a code-scanning tool that no-longer exists under that name. It is now built into GitHub Actions under the name, CodeQL. References to LGTM are in two files: /README.md and /languages/python/README.md.

## Proposed Solution ##
1. Implement CodeQL scanning in all cisagov repositories (if not already done).
2. Update README files to replace references to LGTM with CodeQL.

## Source ##
[The next step for LGTM.com: GitHub code scanning!](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/)
[About code scanning with CodeQL](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql)

**Comment by jsf9k** [comment]
Sharp eyes!

I believe this is already taken care of in #79, which is awaiting re-review by @mcdonnnj.  Please have a look at that PR and let me know if it doesn't actually resolve this issue.

**Comment by Matthew-Grayson** [comment]
Great! Thanks! I'm closing this issue since it is already covered in #79.
